services:
  nginx:
    depends_on:
      - pong
    build: ./requirements/nginx
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  pong:
    build: ./requirements/pong
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
