version: "3.9"
services:
  backend:
    container_name: backend_tr
    image: backend:v1.0
    tty: true
    build: docker/backend
    networks:
      - ft_transcendence
    expose:
      - "3000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - APP_ID=${APP_ID}
      - APP_SECRET=${APP_SECRET}
      - AUTH_SECRET=${AUTH_SECRET}
    volumes:
      - ./backend:/var/www/html
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    
  frontend_tr:
    container_name: frontend_tr
    depends_on:
      - backend
    image: frontend
    tty: true
    build: docker/frontend
    networks:
      - ft_transcendence
    expose:
      - "5173"
      - "5174"
    volumes:
      - ./frontend:/var/www/html
    environment:
      - VITE_APP_ID=${APP_ID}
      - VITE_APP_SECRET=${APP_SECRET}
      - VITE_APP_URI=${APP_URI}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  postgres_tr:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "5432:5432"
    networks:
      - ft_transcendence

  adminer:
    container_name: adminer
    image: adminer:v1.0
    tty: true
    build: docker/adminer
    ports:
      - "9002:80"
    networks:
      - ft_transcendence
    volumes:
      - db:/var/lib/postgresql/data
    restart: on-failure
    depends_on:
      - "postgres_tr"
  nginx:
    image: nginx:alpine
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - ft_transcendence
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
    command: [ nginx-debug, "-g", "daemon off;" ]
    ports:
      - "4000:80"
      - "5174:5174"
    depends_on:
      - frontend_tr
      - backend
volumes:
  db:
networks:
  ft_transcendence:
